# github action to build docker container and deploy to ECS 

# on:
#     push:
#         branches: [ master ]

on:
    pull_request:
        branches: [ master ]
    
jobs:
    create-image:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2

            - name: "yarn install"
              uses: borales/actions-yarn@v2.0.0
              with:
                cmd: install --cwd ./client

            - name: "yarn build"
              uses: borales/actions-yarn@v2.0.0
              with:
                cmd: build 
            
            - name: "Build Image"
              run: docker build . --tag texter-image
