# github action to build docker container and deploy to ECS 

# on:
#     push:
#         branches: [ master ]

on:
    pull_request:
        branches: [ master ]
    
jobs:
    create-image:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2

            - name: "Yarn Install"
              uses: borales/actions-yarn@v2.0.0
              with:
                cmd: --cwd ./client install 

            - name: "Client Build"
              uses: borales/actions-yarn@v2.0.0
              with:
                cmd: --cwd ./client run build
            
            - name: "Build Image"
              run: docker build . --tag texter-image
