# git action to run (go) tests on PR

on:
    pull_request:
        branches: [ master ]
    
jobs:
    go_test_pull_request:
        runs-on: ubuntu-latest
        steps: 
            - name: set up go
              uses: actions/setup-go@v2
              with:
                go-version: '^1.13.1'

            - name: checkout 
              uses: actions/checkout@v2

            - name: install go deps
              run: go get -v -u github.com/${GITHUB_REPOSITORY}

            - name: go test
              run: go test ./...

    # TODO add job for client tests
    # yarn test
