# github action to run tests on PR to master

on:
    pull_request:
        branches: [ master ]
    
jobs:
    go_test_pull_request:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/setup-go@v2
              with:
                go-version: '^1.13.1'

            - uses: actions/checkout@v2

            - name: Install Golang Deps
              run: go get -v -u github.com/${GITHUB_REPOSITORY}

            - run: go test ./...

    # TODO add job for client tests
    # yarn test
